[package]
name = "fasthash-fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.fasthash]
path = "../fasthash"

[dependencies.fasthash-sys]
path = "../fasthash-sys"

[workspace]

